export const QUERY_KEYS = {
  REFRESH_CHAT_TOKEN: "REFRESH_CHAT_TOKEN",
  GET_IMAGE_COLLECTION: "GET_IMAGE_COLLECTION",
  GET_SESSION_SUMMARY: "GET_SESSION_SUMMARY",
  GET_SESSION_BY_TAG_OR_STATUS: "GET_SESSION_BY_TAG_OR_STATUS",
};
