export const QUERY_KEYS = {
  REFRESH_CHAT_TOKEN: "REFRESH_CHAT_TOKEN",
  GET_SESSION_SUMMARY: "GET_SESSION_SUMMARY",
  GET_SESSION_BY_TAG_OR_STATUS: "GET_SESSION_BY_TAG_OR_STATUS",
  SEARCH_MESSAGE: "SEARCH_MESSAGE",
};
